/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiCheckinsRouteImport } from './routes/api/checkins'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiWorkoutsRouteImport } from './routes/api/workouts'
import { Route as ApiAgentContextRouteImport } from './routes/api/agent/context'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinsRoute = ApiCheckinsRouteImport.update({
  id: '/api/checkins',
  path: '/api/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutsRoute = ApiWorkoutsRouteImport.update({
  id: '/api/workouts',
  path: '/api/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentContextRoute = ApiAgentContextRouteImport.update({
  id: '/api/agent/context',
  path: '/api/agent/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workouts': typeof ApiWorkoutsRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workouts': typeof ApiWorkoutsRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workouts': typeof ApiWorkoutsRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/health'
    | '/api/workouts'
    | '/api/agent/context'
    | '/api/auth/login'
    | '/api/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/health'
    | '/api/workouts'
    | '/api/agent/context'
    | '/api/auth/login'
    | '/api/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/health'
    | '/api/workouts'
    | '/api/agent/context'
    | '/api/auth/login'
    | '/api/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiCheckinsRoute: typeof ApiCheckinsRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkoutsRoute: typeof ApiWorkoutsRoute
  ApiAgentContextRoute: typeof ApiAgentContextRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkins': {
      id: '/api/checkins'
      path: '/api/checkins'
      fullPath: '/api/checkins'
      preLoaderRoute: typeof ApiCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workouts': {
      id: '/api/workouts'
      path: '/api/workouts'
      fullPath: '/api/workouts'
      preLoaderRoute: typeof ApiWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/context': {
      id: '/api/agent/context'
      path: '/api/agent/context'
      fullPath: '/api/agent/context'
      preLoaderRoute: typeof ApiAgentContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiCheckinsRoute: ApiCheckinsRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkoutsRoute: ApiWorkoutsRoute,
  ApiAgentContextRoute: ApiAgentContextRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
