/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as ApiCheckinsRouteImport } from './routes/api/checkins'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiProgressPhotosRouteImport } from './routes/api/progress-photos'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiAgentContextRouteImport } from './routes/api/agent/context'
import { Route as ApiAgentQueryRouteImport } from './routes/api/agent/query'
import { Route as ApiAgentStateRouteImport } from './routes/api/agent/state'
import { Route as ApiProgressPhotosPhotoIdRouteImport } from './routes/api/progress-photos/$photoId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const ApiCheckinsRoute = ApiCheckinsRouteImport.update({
  id: '/api/checkins',
  path: '/api/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressPhotosRoute = ApiProgressPhotosRouteImport.update({
  id: '/api/progress-photos',
  path: '/api/progress-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentContextRoute = ApiAgentContextRouteImport.update({
  id: '/api/agent/context',
  path: '/api/agent/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentQueryRoute = ApiAgentQueryRouteImport.update({
  id: '/api/agent/query',
  path: '/api/agent/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStateRoute = ApiAgentStateRouteImport.update({
  id: '/api/agent/state',
  path: '/api/agent/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressPhotosPhotoIdRoute =
  ApiProgressPhotosPhotoIdRouteImport.update({
    id: '/$photoId',
    path: '/$photoId',
    getParentRoute: () => ApiProgressPhotosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRouteWithChildren
  '/api/reports': typeof ApiReportsRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/agent/query': typeof ApiAgentQueryRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/progress-photos/$photoId': typeof ApiProgressPhotosPhotoIdRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRouteWithChildren
  '/api/reports': typeof ApiReportsRoute
  '/': typeof AppIndexRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/agent/query': typeof ApiAgentQueryRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/progress-photos/$photoId': typeof ApiProgressPhotosPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRouteWithChildren
  '/api/reports': typeof ApiReportsRoute
  '/_app/': typeof AppIndexRoute
  '/api/agent/context': typeof ApiAgentContextRoute
  '/api/agent/query': typeof ApiAgentQueryRoute
  '/api/agent/state': typeof ApiAgentStateRoute
  '/api/progress-photos/$photoId': typeof ApiProgressPhotosPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/reports'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/export'
    | '/api/health'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/reports'
    | '/api/agent/context'
    | '/api/agent/query'
    | '/api/agent/state'
    | '/api/progress-photos/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/reports'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/export'
    | '/api/health'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/reports'
    | '/'
    | '/api/agent/context'
    | '/api/agent/query'
    | '/api/agent/state'
    | '/api/progress-photos/$photoId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/profile'
    | '/_app/reports'
    | '/api/checkins'
    | '/api/dashboard'
    | '/api/export'
    | '/api/health'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/reports'
    | '/_app/'
    | '/api/agent/context'
    | '/api/agent/query'
    | '/api/agent/state'
    | '/api/progress-photos/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiCheckinsRoute: typeof ApiCheckinsRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProgressPhotosRoute: typeof ApiProgressPhotosRouteWithChildren
  ApiReportsRoute: typeof ApiReportsRoute
  ApiAgentContextRoute: typeof ApiAgentContextRoute
  ApiAgentQueryRoute: typeof ApiAgentQueryRoute
  ApiAgentStateRoute: typeof ApiAgentStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/checkins': {
      id: '/api/checkins'
      path: '/api/checkins'
      fullPath: '/api/checkins'
      preLoaderRoute: typeof ApiCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress-photos': {
      id: '/api/progress-photos'
      path: '/api/progress-photos'
      fullPath: '/api/progress-photos'
      preLoaderRoute: typeof ApiProgressPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/context': {
      id: '/api/agent/context'
      path: '/api/agent/context'
      fullPath: '/api/agent/context'
      preLoaderRoute: typeof ApiAgentContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/query': {
      id: '/api/agent/query'
      path: '/api/agent/query'
      fullPath: '/api/agent/query'
      preLoaderRoute: typeof ApiAgentQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/state': {
      id: '/api/agent/state'
      path: '/api/agent/state'
      fullPath: '/api/agent/state'
      preLoaderRoute: typeof ApiAgentStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress-photos/$photoId': {
      id: '/api/progress-photos/$photoId'
      path: '/$photoId'
      fullPath: '/api/progress-photos/$photoId'
      preLoaderRoute: typeof ApiProgressPhotosPhotoIdRouteImport
      parentRoute: typeof ApiProgressPhotosRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiProgressPhotosRouteChildren {
  ApiProgressPhotosPhotoIdRoute: typeof ApiProgressPhotosPhotoIdRoute
}

const ApiProgressPhotosRouteChildren: ApiProgressPhotosRouteChildren = {
  ApiProgressPhotosPhotoIdRoute: ApiProgressPhotosPhotoIdRoute,
}

const ApiProgressPhotosRouteWithChildren =
  ApiProgressPhotosRoute._addFileChildren(ApiProgressPhotosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiCheckinsRoute: ApiCheckinsRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiExportRoute: ApiExportRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProgressPhotosRoute: ApiProgressPhotosRouteWithChildren,
  ApiReportsRoute: ApiReportsRoute,
  ApiAgentContextRoute: ApiAgentContextRoute,
  ApiAgentQueryRoute: ApiAgentQueryRoute,
  ApiAgentStateRoute: ApiAgentStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
